name       : perl-xml-twig
version    : 3.49
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MI/MIROD/XML-Twig-3.49.tar.gz : 3e0def8a7477fefa8c27fabf11899a459c8b793909182d016ba26749e9354e01
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Perl XML module
description: |
    This module provides a way to process XML documents. It is build on top of XML::Parser.
builddeps  :
    - perl
    - perl-xmlparser
rundeps    :
    - perl-xmlparser
setup      : |
    perl Makefile.PL -y PREFIX=/usr INSTALLDIRS=vendor DESTDIR=$installdir
build      : |
    %perl_build
install    : |
    %perl_install
